### 3. 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산
    - 벡터: 한 가지 타입의 여러 개의 원소를 변수에 저장한 배열을 의미
    - 벡터화 연산: 벡터의 같은 인덱스에 위치한 원소들끼리 연산을 수행하는 기능 /리스트통째로 값연산 가능
        - 반복문을 사용하지 않고도 반복해서 연산이 가능


In [2]:
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [3]:
a1+a1 # 변수를 한번더 더한값을 반환

array([0, 2, 4, 6, 8])

In [71]:
x = np.arange(1,101)
y = np.arange(1101,1201)
z = x + y
z[:5]
# array([1102,1104,1106,1108,1110])

array([1102, 1104, 1106, 1108, 1110])

In [72]:
z = 3 * x
z[:5]

array([ 3,  6,  9, 12, 15])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [7]:
a >= b

array([False,  True,  True,  True])

In [8]:
a / b

array([0.25, 1.  , 1.5 , 1.  ])

In [9]:
# 로그함수 (logarithmic function), 지수함수(exponential function)
np.log(a),np.exp(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [10]:
c = np.arange(6).reshape(2,3)
np.exp(c)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [11]:
c+3 # 모든항에 3이 더해짐 스칼라의 덧셈

array([[3, 4, 5],
       [6, 7, 8]])

- 차원 축소 연산

In [12]:
# x = array([1, 2, 3, 4])
x = np.arange(1,5)
np.sum(x)   # sum numpy의 함수로 부르기 

10

In [13]:
x.sum()     # numpy 객체의 메소드로 부르기

10

In [14]:
# 최소값,최대값
x.min(), x.max()

(1, 4)

In [15]:
# 대표값: 평균,중앙값(median),최빈값
# 최빈값: 나타나는빈도가 가장많은값 - 보통카테고리형데이터 ex) 1등실에 10명,2등실에 30명,3등실에 100명의 최빈값은 3등실
x.mean() , np.median(x) 

(2.5, 2.5)

- all or any

In [16]:
np.all(np.array([True, False, True])) # 모든 원소가 참이냐?
# 이 모든게 True냐

False

In [17]:
np.any(np.array([True, False, True])) # 하나라도 참인 원소가 있느냐?

True

- 2차원 이상의 연산

In [18]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# 모든 원소의 합
np.sum(a)

21

In [20]:
# 행 방향으로 합을 구해라 (위에서 아래로), 평균
np.sum(a,axis=0) ,np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [21]:
np.mean(a)

3.5

In [22]:
# 열 방향으로 합, 평균
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

- agmax,argmin
    - 몇번째 인덱스가 max,min인지 인덱스 번호를 알려줌

In [23]:
x = np.array([3,12,33,9,51,26])
np.argmax(x), np.argmin(x)
# 몇번째 인덱스가 max,min인지 인덱스 번호를 알려줌

(4, 0)

In [24]:
y = x.reshape(2,3)
np.argmax(y, axis=0), np.argmin(y,axis=0)
# argmax에서 1로 max위치표시 / argmin은 0으로 min위치표시

(array([1, 1, 0], dtype=int64), array([0, 0, 1], dtype=int64))

In [25]:
y

array([[ 3, 12, 33],
       [ 9, 51, 26]])

- 연습문제 3.3.1

In [26]:
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

xf = np.arange(1,31).reshape(5,6).astype(float)
xf

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [27]:
np.random.seed(2023) # random seed값을 먹기 때문에........ random이어도 값이 정해져있는것
np.set_printoptions(precision=4, suppress=True) # 자리수4로 정해줌
m = np.random.random(30).reshape(5,6)
m

array([[0.322 , 0.8904, 0.5881, 0.1266, 0.1413, 0.4679],
       [0.0221, 0.7273, 0.5244, 0.5449, 0.4564, 0.5014],
       [0.3945, 0.1512, 0.3609, 0.1621, 0.338 , 0.1803],
       [0.391 , 0.0356, 0.5649, 0.2035, 0.3206, 0.3766],
       [0.1841, 0.104 , 0.4549, 0.1959, 0.3785, 0.9305]])

In [28]:
xf.dtype

dtype('float64')

In [29]:
# 전체의 최댓값 방법1
xf.max() # 방법2= np.max(xf) 

30.0

In [30]:
# 방법3
np.round(np.max(xf),4)

30.0

In [31]:
# 각 행의 합
np.sum(xf, axis=1) 

array([ 21.,  57.,  93., 129., 165.])

In [32]:
# 각 행의 최댓값
np.max(xf, axis=1)

array([ 6., 12., 18., 24., 30.])

In [33]:
# 각 열의 평균
np.mean(xf, axis=0)

array([13., 14., 15., 16., 17., 18.])

In [34]:
# 각 열의 최솟값
np.min(xf, axis=0)

array([1., 2., 3., 4., 5., 6.])

- 정렬
    - 함수 np.sort()
    - 메소드 a.sort()

In [36]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [38]:
# sort()는 axis=1 열방향(좌에서우) default
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [39]:
# 행방향으로 정렬
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [40]:
# a는 바뀌지 않았음
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [42]:
# sort() method는 자기 파괴적(in-place) method이다. / a가 바뀜
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [45]:
# argsort 위치위치위치
a = np.array([[4, 3, 5, 7],[1, 12, 11, 9],[2, 15, 1, 14]])
j = np.argsort(a)
j
# 작은수부터 인덱스를 0으로 시작해서 그 위치를 알려주는것. 위치순서를 알려주는
''' 
4,3,5,7
4는 1번째로 작고
3은 0번째로 작고
5는 2번째로 작고
7은 3번째로 작다
그래서 인덱스의 순서(위치)를 알려준다.
1,0,2,3
'''

array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [46]:
# 내림차순 정렬(열 방향)
np.sort(a)[:, ::-1]


array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [48]:
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [50]:
# 내림차순 정렬 (행 방향)
np.sort(a, axis=0)[::-1,:]

array([[ 4, 15, 11, 14],
       [ 2, 12,  5,  9],
       [ 1,  3,  1,  7]])

다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

In [51]:
s = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71],
              [ 81,   59,   90,  100]])

In [63]:
np.argsort(s)
''' 
46,99,100,71
46,71,99,100
46은 0번쨰로 작은데 인덱스0 위치
71은 1번째로 작은데 인덱스3 위치
99는 2번째로 작은데 인덱스1 위치
100은 3번째로 작은데 인덱스2 위치
그래서
0,3,1,2
-----------
81,59,90,100
59,81,90,100
1,0,2,3
'''

array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]], dtype=int64)

In [60]:
# 영어 성적을 argsort() 하여 인덱스를 구함
indices = np.argsort(s[1]) # 영어성적만
indices

array([0, 3, 1, 2], dtype=int64)

In [61]:
# 인덱스를 내림차순으로 정렬
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [62]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
s[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [64]:
# 한줄로
s[:,np.argsort(s[1])[::-1]] # indices = np.argsort(s[1])[::-1]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])