### 5.난수 발생과 카운팅

In [1]:
import numpy as np

- Sedd 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링

    - 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 혹은 샘플링(sampling)이라고 한다. 샘플링에는 `choice` 함수를 사용한다. `choice` 함수는 다음과 같은 인수를 가질 수 있다.


`numpy.random.choice(a, size=None, replace=True, p=None)`

* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
* p : 배열. 각 데이터가 선택될 수 있는 확률


In [5]:
np.random.choice(5,5,replace=False)

array([3, 4, 0, 2, 1])

In [7]:
x = np.random.randint(1,100,10)
x

array([71, 16, 89, 73, 48, 66, 72, 23, 54,  8])

In [11]:
x = np.random.choice(x,5,replace=False)
x

array([3, 3, 4, 4, 0])

- 난수 생성
    - 넘파이의 random 서브패키지는 이외에도 난수를 생성하는 다양한 함수를 제공한다. 그 중 가장 간단하고 많이 사용되는 것은 다음 3가지 함수다.

* `rand`: 0부터 1사이의 균일 분포 
* `randn`: 표준 정규 분포
* `randint`: 균일 분포의 정수 난수

In [12]:
# random() - Uniform(균등하게)분포, 0~ 1 사이의 값
np.random.random(10)

array([0.39172036, 0.11004811, 0.9127915 , 0.35700599, 0.41296218,
       0.18354969, 0.58599027, 0.85567085, 0.78968122, 0.08784242])

In [13]:
# randint(low,high,N) - [low, high) 범위가 low는 포함하고 high는 포함하지 않는다. N은 N개 꺼내라
# low<= x < high는 [low, high) 이렇게 표현한다..
np.random.randint(1,7,10)

array([5, 3, 5, 1, 5, 2, 4, 5, 1, 5])

In [14]:
# normal(평균, 표준편차, 도수N) - 정규분포
np.random.normal(170,10,10)

array([181.67226207, 163.97585636, 166.24095837, 167.08713359,
       160.01620207, 176.03242369, 166.58776424, 169.65713669,
       183.31161153, 157.14453006])

In [15]:
# randn(N) - 표준정규분포 N(0,1)
np.random.randn(10)

array([ 0.55215289,  1.09259703,  1.77210263, -0.1137414 , -1.39798223,
       -0.38444907,  0.45366873, -1.01517303,  0.16824259, -1.26226678])

In [16]:
# binomial(시도횟수,평균, N) 이항분포 B(N, p)
np.random.binomial(10,0.5,20).reshape(4,5)

array([[5, 6, 8, 4, 6],
       [5, 5, 6, 2, 1],
       [6, 6, 4, 7, 3],
       [4, 3, 6, 6, 2]])

In [17]:
# 가설 검정: t - 검정
# standard_t(자유도,개수)
np.random.standard_t(2,10)


array([-4.69351722,  0.87950312, 13.60655061, -0.26102413, -1.32482054,
       -1.26550017, -0.82598883, -1.17519698,  0.63656836, -1.01826889])

In [19]:
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
np.random.binomial(1,0.5,10) # 1번던질때 0.5의 확률로 10번던진다.

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0])

In [21]:
# 주사위를 100번 던져서 나오는 숫자의 평균(mean)을 구하라.
np.mean(np.random.randint(1,7,100))


3.57

In [ ]:
'''
가격이 10,000원인 주식이 있다. 
이 주식의 일간 수익률(%)은 
기댓값이 0%이고 
표준편차가 1%인 
표준 정규 분포를 따른다고 하자. 
250일 동안의 주가를 무작위로 생성하라

기대값 = 평균 = 0
수익율 1% = 0.01
normal(0,0.01,250)

normal(평균, 표준편차, 도수N) - 정규분포
np.random.normal(170,10,10)
10000
1%: 10100 -1%: 9900
-1%: 9999 +1%: 9999
'''

In [35]:
rate = np.random.normal(0,0.01,5)
rate


array([-0.005399  ,  0.02211261,  0.00593662, -0.00154573, -0.00608435])

In [37]:
price = 10000
price = price + price * rate[0]     # =  price * (1 + rate[0])
int(np.round(price))    # np.round 소수점 반올림하고 int정수로 변환

9946

In [39]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])
    price = int(np.round(price)) 
    print(price, end=' ')

9946 10166 10226 10210 10148 

In [40]:
# 우리가 알던 방법 list로 해결
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [42]:
# 우리가 알던 방법 list로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price)) 
    price_list.append(price)

price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [45]:
# 2. array로 해결
price_array2 = np.zeros(250, dtype=int)
price = 10000
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price)) 
    price_array2[i] = price

price_array2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [41]:
#지우기
(1 + np.random.randn(5)/100) * 10000

array([ 9753.78347673, 10150.48019299,  9993.8505649 , 10043.48859175,
       10020.2030989 ])

In [30]:
#지우기
n = 10000
x = np.random.randn(250)
for i in x:
    n = n * (1 + (i / 100))
print("{:,}원".format(round(n)))

10,188원


In [31]:
#지우기
profit_rand = np.random.randn(250)*0.01
price = 10000

for i in profit_rand:
    price += price*i

price

10814.433085380013

- 데이터 카운팅

In [47]:
dices = np.random.randint(1,7,100)
np.unique(dices) # 고유한값 알려줘라

array([1, 2, 3, 4, 5, 6])

In [48]:
np.unique(dices, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([12, 28, 17, 13, 14, 16], dtype=int64))

In [49]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([12, 28, 17, 13, 14, 16], dtype=int64))

In [51]:
indices * count

array([12, 56, 51, 52, 70, 96], dtype=int64)

In [54]:
# 주사위 평균
np.sum (indices * count) / np.sum(count)

3.37

In [55]:
np.sum (indices * count) / 100 # 100번돌린거라

3.37

In [56]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [57]:
index , count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [58]:
np.bincount(dices, minlength=6)

array([ 0, 12, 28, 17, 13, 14, 16], dtype=int64)