### 1. Series
    - 데이터를 리스트나 1차원 배열 형식으로 Series 클래스 생성자에 넣어주면 시리즈 클래스 객체를 만들 수 있다. 
    - 이 때 인덱스의 길이는 데이터의 길이와 같아야 한다. 
    - 다음 예에서 이 “서울”, “부산” 등의 문자열이 인덱스의 값이다. 인덱스의 값을 인덱스 라벨(label)이라고도 한다. 인덱스 라벨은 문자열 뿐 아니라 날짜, 시간, 정수 등도 가능하다

In [1]:
import numpy as np
import pandas as pd

- Series 생성
    - numpy 1차원 어레이 + index

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울","부산","인천","대구"])
s


서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
type(s)

pandas.core.series.Series

In [4]:
# 인덱스 지정안하면 자동으로 0,1,2,.... 으로 간다.
# 인덱스를 별도로 설정하지 않으면, 인덱스는 0,1,2, ... 이 된다.
pd.Series(np.arange(10,15))

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [5]:
s.index , type(s.index) # numpy array로 끄지어옴

(Index(['서울', '부산', '인천', '대구'], dtype='object'),
 pandas.core.indexes.base.Index)

In [6]:
s.values , type(s.values)   # numpy array로 끄지어옴

(array([9904312, 3448737, 2890451, 2466052], dtype=int64), numpy.ndarray)

In [7]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

- 연산(Operation)

In [8]:
s / 10000000 # data가 numpy라 data연산이 가능하다

도시
서울    0.990431
부산    0.344874
인천    0.289045
대구    0.246605
Name: 인구, dtype: float64

- 인덱싱

In [9]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [10]:
# 이름으로 인덱싱,
s['부산'], s[1],  s.부산  # 결과가 scalar값

(3448737, 3448737, 3448737)

In [11]:
s['대구'],s[3],s[-1], s.대구

(2466052, 2466052, 2466052, 2466052)

In [12]:
# 반드시 리스트형태로 들어와줘야함 [[]]
s[[0, 1]]   # 결과가 Series값

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [13]:
s[['서울', '부산']]

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [14]:
s[(s > 2500000) & (s < 5000000)] # 250만 초과 500만 미만

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [15]:
s[s > 5000000]

도시
서울    9904312
Name: 인구, dtype: int64

- 슬라이싱

In [16]:
# 숫자 인덱스로 하는 슬라이싱은 넘파이와 동일
s[:2]

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [17]:
# 인덱스 문자열로 하는 경우에는 :콜론 뒤 인덱스를 포함
s['서울':'인천']

도시
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64

- 시리즈와 딕셔너리
    - 딕셔너리 자료형에서 제공하는 in 연산도 가능하고 items 메서드를 사용하면 for 루프를 통해 각 원소의 키(key)와 값(value)을 접근할 수도 있다.

In [18]:
'서울' in s

True

In [19]:
for k,v in s.items():
    print(f'{k}: {v}')

서울: 9904312
부산: 3448737
인천: 2890451
대구: 2466052


In [20]:
d = {"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}
s2 = pd.Series(d)
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [21]:
# 딕셔너리의 원소는 순서를 가지지 않으므로 시리즈의 데이터도 순서가 보장되지 않는다. 
# 만약 순서를 정하고 싶다면 인덱스를 리스트로 지정해야 한다

In [22]:
# 순서를 정하고 싶으면, 인덱스를 별도로 설정해야 함
s2 = pd.Series(d, index=['서울','부산','인천','대전'])
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 인덱스 기반 연산

In [23]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [24]:
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [25]:
# 동일한 인덱스를 찾아서 data를 빼고 동일한 인덱스가 없다면 NaN
# 부산,서울,인천 data보면 실수로 바뀜
# NaN 값이 float 자료형에서만 가능하므로 다른 계산 결과도 모두 float 자료형이 되었다는 점에 주의
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [26]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [27]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [28]:
# 인구 증가율(%)
rs = (s-s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

- 데이터의 갱신,추가,삭제

In [29]:
s2 

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [30]:
# 갱신,update
rs['부산'] = 1.64
rs[1] = 2.83
rs.인천 = 9.82
rs

부산    1.64
서울    2.83
인천    9.82
dtype: float64

In [32]:
# 추가
rs['광주'] = 1.51   # rs.광주, rs[2] 는 사용할 수 없음
rs

부산    1.64
인천    9.82
광주    1.51
dtype: float64

In [31]:
# 삭제
del rs['서울']  # rs.인천, rs[2] 는 사용할 수 없음
rs

부산    1.64
인천    9.82
dtype: float64

In [47]:
#  임의로 두 개의 시리즈 객체를 만든다. 모두 문자열 인덱스를 가져야 하며 두 시리즈에 공통적으로 포함되지 않는 라벨이 있어야 한다.
a = pd.Series([100, 200, 300, 400, 500],
              index=["월","화","수","목", "금"])
b = pd.Series([11, 22, 33, 44],
              index=["월","화","수","목"])
a, b

(월    100
 화    200
 수    300
 목    400
 금    500
 dtype: int64,
 월    11
 화    22
 수    33
 목    44
 dtype: int64)

In [48]:
#  위에서 만든 두 시리즈 객체를 이용하여 사칙 연산을 한다.
a+b ,a-b ,a/b, a*b # NaN땜에 data실수

(금      NaN
 목    444.0
 수    333.0
 월    111.0
 화    222.0
 dtype: float64,
 금      NaN
 목    356.0
 수    267.0
 월     89.0
 화    178.0
 dtype: float64,
 금         NaN
 목    9.090909
 수    9.090909
 월    9.090909
 화    9.090909
 dtype: float64,
 금        NaN
 목    17600.0
 수     9900.0
 월     1100.0
 화     4400.0
 dtype: float64)

- 중요한 method

In [49]:
dice = pd.Series(np.random.randint(1,7,10))
dice

0    1
1    2
2    2
3    6
4    3
5    3
6    2
7    3
8    2
9    1
dtype: int32

In [50]:
# element의 개수
dice.count()

10

In [51]:
# 고유한 값
dice.unique()

array([1, 2, 6, 3])

In [52]:
# 고유한 값의 개수
dice.nunique()

4

In [53]:
# 고유한 값 별로 개수 확인방법1
dice.value_counts()

2    4
3    3
1    2
6    1
Name: count, dtype: int64

In [54]:
# 고유한 값 별로 개수 확인방법2
np.unique(dice.values, return_counts=True)

(array([1, 2, 3, 6]), array([2, 4, 3, 1], dtype=int64))

In [55]:
# 최소값, 최대값, 합, 중간값
dice.min(), dice.max(), dice.sum(), dice.mean()

(1, 6, 25, 2.5)

In [56]:
# 요약 기술통계
dice.describe()

count    10.000000
mean      2.500000
std       1.433721
min       1.000000
25%       2.000000
50%       2.000000
75%       3.000000
max       6.000000
dtype: float64

In [57]:
# sort
dice.sort_values()

0    1
9    1
1    2
2    2
6    2
8    2
4    3
5    3
7    3
3    6
dtype: int32

In [58]:
# 데이터 기준 오름차순
s.sort_values()

도시
대구    2466052
인천    2890451
부산    3448737
서울    9904312
Name: 인구, dtype: int64

In [59]:
# 데이터 기준 내림차순
s.sort_values(ascending=False)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [60]:
# 인덱스 기준 오름차순
s.sort_index()

도시
대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 인구, dtype: int64

In [61]:
# 인덱스 기준 내림차순
s.sort_index(ascending=False)

도시
인천    2890451
서울    9904312
부산    3448737
대구    2466052
Name: 인구, dtype: int64

In [62]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [63]:
# inplace옵션을 True로 하면 자기 파괴적 메소드가 됨
s.sort_index(inplace=True)
s

도시
대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 인구, dtype: int64

- 결측치(Na, NaN, Null) 처리

In [64]:
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [65]:
# notnull이랑 반대
ds.isna()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [66]:
ds.isnull()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [67]:
# 0이 아닌 값이 나오면 데이터 안에 결측치가 있음
ds.isna().sum() # True인게 2개 있구나 결측치가 2개있구나

2

In [68]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class   
0         0       3    male  22.0      1      0   7.2500        S  Third  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [75]:
survived = titanic['survived']
age = titanic['age']

In [78]:
survived.isna().sum()   # 결측치가 없음

0

In [79]:
age.isna().sum()    # 결측치가 177개 있음

177

In [81]:
survived.count()    # 결측치를 제외한 데이터 개수

891

In [ ]:
'''
많은 데이터가 결측치
900개중 500개 결측치 - 버린다

적당한 데이터가 결측치
1.결측치만 제거 - dropna()메소드사용
2. 결측치를 대체 -평균,중앙값,최빈값 -fillna()메소드 사용
'''

In [84]:
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [86]:
# 결측치를 제거
ds.dropna(inplace=True) # inplace=True하면 결측치 아예제거 ds재출력시에도 결측치 사라진상태
ds

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [87]:
ds

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [88]:
# ds삭제돼서 다시 ds쓰려고 연산 다시함
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [89]:
# 결측치를 중앙값으로 대체
ds.fillna(ds.median())

대구    258416.0
대전    258416.0
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [92]:
# 결측치를 평균값으로 대체하고 ds를 변경
ds.fillna(ds.mean(), inplace=True)
ds

대구    195597.333333
대전    195597.333333
부산     55546.000000
서울    272830.000000
인천    258416.000000
dtype: float64

In [94]:
# 결측치를 0으로 설정하고 , 데이터 타입을 정수형으로 변경
ds = s - s2
ds = ds.fillna(0).astype(int)
ds

대구         0
대전         0
부산     55546
서울    272830
인천    258416
dtype: int32